import { Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { cookies } from "next/headers";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookiesStore = await cookies();
  const theme = cookiesStore.get("theme");
  console.log(theme);
  return (
    <html lang="en" className={theme?.value || "dark"}>
      <body
        className={`${nunitoSans.className} ${geistMono.variable} antialiased relative min-h-dvh bg-background dark:bg-very-dark`}
      >
        <Header />
        <div className="pt-25">{children}</div>
      </body>
    </html>
  );
}
