import { Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} ${geistMono.variable} antialiased relative  `}
      >
        <Header />
        <div className="pt-25">{children}</div>
      </body>
    </html>
  );
}
